version: '3.8'
services:
  ds:
    container_name: ds
    build: ./../discovery-service
    image: finances_ds
    ports:
      - 8761:8761  
  cf:
    container_name: cf
    build: ./../config-service
    image: finances_cf
    ports:
      - 8888:8888
    environment: 
      - WAIT_HOSTS=ds:8761
    depends_on: 
      - ds
  us:
    container_name: us
    build: ./../user-service
    image: finances_us
    ports:
      - 8081:8081
    environment: 
      - MONGO_URI=mongodb+srv://finances:finances@cluster0.1n7zl.mongodb.net/users
      - WAIT_HOSTS=ds:8761,cf:8888
    depends_on:
      - cf
      - ds 
  cs:
    container_name: cs
    build: ./../category-service
    image: finances_cs
    ports:
      - 8082:8082
    environment: 
      - MONGO_URI=mongodb+srv://finances:finances@cluster0.1n7zl.mongodb.net/categories
      - WAIT_HOSTS=ds:8761,cf:8888
    depends_on:
      - cf
      - ds
  inc:
    container_name: inc
    build: ./../income-service
    image: finances_inc
    ports:
      - 8083:8083
    environment: 
      - MONGO_URI=mongodb+srv://finances:finances@cluster0.1n7zl.mongodb.net/incomes
      - WAIT_HOSTS=ds:8761,cf:8888
    depends_on:
      - cf
      - ds
  exp:
    container_name: exp
    build: ./../expense-service
    image: finances_exp
    ports:
      - 8084:8084
    environment: 
      - MONGO_URI=mongodb+srv://finances:finances@cluster0.1n7zl.mongodb.net/expenses
      - WAIT_HOSTS=ds:8761,cf:8888
    depends_on:
      - cf
      - ds
  bud:
    container_name: bud
    build: ./../budget-service
    image: finances_bud
    ports:
      - 8085:8085
    environment: 
      - MONGO_URI=mongodb+srv://finances:finances@cluster0.1n7zl.mongodb.net/budgets
      - WAIT_HOSTS=ds:8761,cf:8888
    depends_on:
      - cf
      - ds
  gw:
    container_name: gw
    build: ./../gateway-service
    ports:
      - 80:80
    environment:
      - WAIT_HOSTS=ds:8761,cf:8888
networks: 
  default:
    name: finances