version: '3.8'
services:
  db:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes: 
      - mongodata:/data/db
  ds:
    container_name: ds
    build: ./../discovery-service
    image: finances_ds
    expose:
      - 8761
  gw:
    container_name: gw
    build: ./../gateway-service
    image: finances_gw
    expose:
      - 443
    ports:
      - 443:443
    environment:
      - EUREKA_SERVER=http://ds:8761/eureka
      - OKTA_OAUTH2_CLIENT_ID=${OKTA_ID}
      - OKTA_OAUTH2_CLIENT_SECRET=${OKTA_SECRET}
      - WAIT_HOSTS=ds:8761
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY_STORE=/app/keystore.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=${CERT_PASSWORD}
      - SERVER_SSL_KEY_ALIAS=finances
      - SERVER_SSL_KEY_STORE_TYPE=PKCS12
    depends_on: 
      - ds
  us:
    container_name: us
    build: ./../user-service
    image: finances_us
    expose:
      - 8081
    environment:
      - EUREKA_SERVER=http://ds:8761/eureka 
      - WAIT_HOSTS=ds:8761,mongodb:27017
    depends_on:
      - ds
      - db 
  cs:
    container_name: cs
    build: ./../category-service
    image: finances_cs
    expose:
      - 8082
    environment:
      - EUREKA_SERVER=http://ds:8761/eureka 
      - WAIT_HOSTS=ds:8761,mongodb:27017
    depends_on:
      - ds
      - db
  inc:
    container_name: inc
    build: ./../income-service
    image: finances_inc
    expose:
      - 8083
    environment:
      - EUREKA_SERVER=http://ds:8761/eureka 
      - WAIT_HOSTS=ds:8761,mongodb:27017
    depends_on:
      - ds
      - db
  exp:
    container_name: exp
    build: ./../expense-service
    image: finances_exp
    expose:
      - 8084
    environment:
      - EUREKA_SERVER=http://ds:8761/eureka 
      - WAIT_HOSTS=ds:8761,mongodb:27017
    depends_on:
      - ds
      - db
  bud:
    container_name: bud
    build: ./../budget-service
    image: finances_bud
    expose:
      - 8085
    environment:
      - EUREKA_SERVER=http://ds:8761/eureka 
      - WAIT_HOSTS=ds:8761,mongodb:27017
    depends_on:
      - ds
      - db
networks: 
  default:
    name: finances
volumes: 
  mongodata: