apiVersion: v1
data:
  POSTGRES_PASSWORD: MTIzNDU2
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMuZmluYW5jZXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9maW5hbmNlcw==
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
type: Opaque
metadata:
  annotations:
    app: finances-easy-api
  name: finances-easy-api-secret
  namespace: finances
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finances-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: finances-easy-api-svc
            port:
              number: 8089
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finances-web-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finances-easy-web-svc
            port:
              number: 80