kind: Secret
apiVersion: v1
metadata:
  annotations:
    app: finances-easy-api
  name: finances-easy-api-secret
  namespace: finances
type: Opaque
data:
  POSTGRES_PASSWORD: MmM2ZmFkZjc5NmZkMDE2M2U0YjZhOTkyZmQ0YThkNTdiZGU4ZTE1OTgxNmM0ZDdmZDJhMTljODQ2MzAwNDEzMA==
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZmluYW5jZXMtZGIuY2FwZnZiaHU4amZhLmV1LXdlc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2ZpbmFuY2Vz
  POSTGRES_USER: cG9zdGdyZXM=