apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finances-easy-ingress
  namespace: finances
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.finances-easy.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: finances-easy-api-svc
            port:
              number: 8089
  - host: finances-easy.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: finances-easy-web-svc
            port:
              number: 80